version: "2"
services:
  postgres:
    container_name: hr_postgres_database
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=dataarchitect
      - POSTGRES_PASSWORD=dataarchitect
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      # - ./scripts/:/scripts/
      - ./scripts/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql

volumes:
  db:
    driver: local
